baseURL = "/"
languageCode = "fr-fr"
title = "My New Hugo Site"
theme = "ctzn"
enableRobotsTXT = true

[params]
    author = "Matthieu"
    owner = "Manu & Matthieu"
    description = "Faites pas chier"
    instagram = "@citizenbarfr"
    facebook = "citizenbarfr"
    twitter = "citizenbarfr"
